apiVersion: v1
kind: Pod
metadata:
  name: app-d
spec:
  containers:
  - name: app-d
    image: azurenamingtooltfregistry.azurecr.io/apia:1.0.0
    imagePullPolicy: IfNotPresent
    resources: {}    
