# POD WITHOUT TOLERATION 
    # - no nodeselector defined
    # - conflict with tainted system mode nodepool

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-task1
  labels:
    app: lab4-task1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab4-task1
  template:
    metadata:
      labels:
        app: lab4-task1
    spec:
      containers:
      - name: api
        image: chineduacr.azurecr.io/apia:v1.1
        imagePullPolicy: IfNotPresent
        resources: {}

---
# POD WITH TOLERATION - works on system nodepool

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: lab4-task3
#   labels:
#     app: lab4-task3
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: lab4-task3
#   template:
#     metadata:
#       labels:
#         app: lab4-task3
#     spec:
#       containers:
#       - name: api
#         image: chineduacr.azurecr.io/apia:v1.1
#         imagePullPolicy: IfNotPresent
#         resources: {}
#       tolerations:
#       - key: "CriticalAddonsOnly"
#         operator: "Equal"
#         value: "true"
#         effect: "NoSchedule"  
#         # PreferNoSchedule : pods wont run and will be pending
#         # NoSchedule: match taint and pods will run

---
# POD with toleration defined
    # -  nodeselector defined
    # - works with tainted system mode nodepool
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-task5
  labels:
    app: lab4-task5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab4-task5
  template:
    metadata:
      labels:
        app: lab4-task5
    spec:
      containers:
      - name: api
        image: chineduacr.azurecr.io/apia:v1.1
        imagePullPolicy: IfNotPresent
        resources: {}
      nodeSelector:
        kubernetes.azure.com/mode: system
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

---
# SPOT NODE PODS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-task7
  labels:
    app: lab4-task7
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab4-task7
  template:
    metadata:
      labels:
        app: lab4-task7
    spec:
      containers:
      - name: api
        image: iacws2<YOUR-NAME>acr.azurecr.io/apia:v1
        imagePullPolicy: IfNotPresent
        resources: {}
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"